# Generated by Django 4.2.5 on 2023-10-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название урока')),
                ('description', models.TextField(verbose_name='описание урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='изображение урока')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
